### ISSUE TITLE
Soil ID (Site) - Implement static site-only content

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1199]
Display the Site Data text block. This is only visible in a Site Location context. See parent task for context and related issues.

## Design
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=6129-21358&mode=design&t=bn4bR0g90ayypnJZ-0) - Site 
<img width="193" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/5590815/532f2a23-a3fe-48f7-b948-a1b4157ba514">

## Acceptance Criteria
- [ ] As any user looking at the Soil ID page of a site, I want to see the content for site data (Site Data header + text, Land Slope header, "Add slope" button, Soil Properties header, "Add Soil Data" button)
- [ ] Users do not see this when looking at the Soil ID page of a Temporary Location

**Non-goals**
- Visuals and data-driven content for Land Slope and Soil Properties 
- Don't worry about exact layout for placing the buttons, and they don't need to work yet (that will be #1200 and #1201)

**Comment by knipec** [comment]
Closing because all of the work of this story is now part of other stories. 
- The text part was done as part of [PR 1265](https://github.com/techmatters/terraso-mobile-client/pull/1265) for Story [#1196](https://github.com/techmatters/terraso-mobile-client/issues/1196). 
- The button parts are being done with their respective stories: [#1230](https://github.com/techmatters/terraso-mobile-client/issues/1230) and [#1200](https://github.com/techmatters/terraso-mobile-client/issues/1200)

**Comment by DerekCaelin** [comment]
Great. Closing as "not planned" because this issue is now a duplicate of other stories.
