### ISSUE TITLE
Color input photo module returns nonvalid results for 7YR 3/1 sample

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1352]
### App Version

125

### Platforms

- [X] iOS
- [x] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

With the same or similar cropping of an image, color input photo module will return different results.

### Steps to Reproduce

1. Download [test color image 7.5YR ](https://drive.google.com/file/d/1TKOg9S9_bsyGhlZ_vHeTH0dThfxUngpT/view?usp=drive_link) onto testing device
2. Go to a site where you are a manager or contributor
3. Select to the "soil" tab and select a color input
4. Select test photo
5. Crop to reference image
6. Crop to 3/1 leaving no white space
7. Select "moist" and "yes" for radio buttons
8. Select analyze
9. see issue

#### Cropping on iPad Image
![image](https://github.com/techmatters/terraso-mobile-client/assets/10799815/240d2c06-dbb0-416b-a966-6015256e84e2)

### Expected behavior

Return results within 1 step of 7.5YR 3/1. 

### Actual behavior

Returns a range of incorrect values, including:
- 5P 8.5/3
- 5R 2/1
- 5PB 5/1
- 10PB 9.5/3
- 10YR 2/1

![image](https://github.com/techmatters/terraso-mobile-client/assets/10799815/b0d03efa-1608-4c2a-8ec3-f336ce99fcd5)
![image](https://github.com/techmatters/terraso-mobile-client/assets/10799815/3c0d4b61-fa84-48b9-983d-4be8dac387aa)
![image](https://github.com/techmatters/terraso-mobile-client/assets/10799815/29d52c82-5c37-4890-a530-5998c3f53556)

### Additional context

Following the same steps on Android the test returns a valid result. On android, if I leave marginal whitespace in the crop zone, the invalid result (5PB 5/1) occurs.

**Comment by CourtneyLee333** [comment]
Updates: I just did some more testing on iPad and got results all over the place. I used the same 7YR 3/1 sample, and experimented with the radio buttons for Moist and Light (though that didn't seem to affect a pattern I could discern.) I used a single depth at each of two different sites. I used the same cropping on all of them. [See the results in Slack.](https://tech-matters.slack.com/archives/C06BQTCAUJF/p1716382018087999)

**Comment by shrouxm** [comment]
update: i am able to reproduce this on my iphone, but not android, so it seems to somehow be a platform specific bug :/ now moving on to to figuring out how to diagnose where in the chain of events the bug is being introduced. i suspect it's because the wrong pixels are being passed into the algorithm rather than that the algorithm is incorrect, but wanna validate that before looking further into a fix

**Comment by CourtneyLee333** [comment]
@shrouxm I also only experience it on iOS. And I had the same thought about it using the wrong cropping, because the colors returned are quite similar to the lighter grey parts of the Munsell page. It doesn't happen every time, which is weird.

**Comment by shrouxm** [comment]
what is confusing to me is that the preview images displayed after you crop are the images being passed into the algorithm, so unless i'm missing something it means that there's a ios-only bug in the function which decodes those images into pixels, which seems challenging to deal with...

i also should note i can reproduce it with other color chips in the same image, and on different images

**Comment by DerekCaelin** [comment]
@shrouxm is this issue still blocked?

**Comment by DerekCaelin** [comment]
Moving this issue into August, since Garo wanted to continue debugging with another Engineer

**Comment by shrouxm** [comment]
finally made some progress on this today. it seems that there are actually two intersecting bugs at play:
- the iOS only bug is that the pixels we get from the image cropping contain some extra junk pixels
- there seems to also be a bug in our color quantization library where it's not returning values that we would expect when there are extra junk pixels at the end of the image

the color quantization library issue seems to also affect the algorithm's robustness (e.g. in situations where due to users fudging the cropping step and leaving some junk pixels in), so next week i plan to:
- write some unit tests that trigger the quantization library's failure state
- test a couple other quantization libraries to see if they work better
- confirm that this bug is no longer reproducible with a different quantization library
- if so, close this ticket

that leaves the question of why we're getting extra junk pixels on iOS unresolved, but i'm not sure what we can do to investigate other than file a bug with expo (which i may do)

**Comment by shrouxm** [comment]
The fix is merged, so this should no longer be reproducible in build numbers 187 and above!

**Comment by DerekCaelin** [comment]
I did this this morning and got a result of 10YR 2/1, which is within 1 step of 7.5YR 3/1. Thanks for this, Garo! Closing.
