### ISSUE TITLE
Opening slope meter crashes app on Android

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#1390]
### App Version

1.0.127

### Platforms

- [ ] iOS
- [X] Android -- Pixel 3a, Android version 12 (as the Pixel 3a no longer gets updates)
- [ ] iOS simulator
- [ ] Android emulator

### Description

Opening slope meter crashes app on Android

### Steps to Reproduce

1. Go to the Slope screen for a site
2. Press the "Slope meter" button

### Expected behavior

Slope meter screen comes up with working camera

### Actual behavior

Slope meter screen very briefly shows up, and then the app crashes

### Additional context

- I don't see this behavior on the Android emulator, the iOS emulator, or my real iOS device
- Brief discussion in [this slack thread](https://tech-matters.slack.com/archives/C0376RCCXD2/p1716308451242919). Also noted by Courtney in [this other slack thread](https://tech-matters.slack.com/archives/C06BQTCAUJF/p1716223456813249).
- I believe this is the [Sentry link](https://techmatters.sentry.io/issues/5380102235/?project=4506299761623040&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0)

**Comment by DerekCaelin** [comment]
I also encounter this issue on a Pixel 7 running Android 14.

## Steps to reproduce
1. Open App
2. Navigate to a site
3. select slope
4. select steepness
5. select the slope meter
6. See issue

## Expected behavior
- camera activates, user can determine slope

## Actual behavior
- camera activates, app runs for ~3s and closes
https://github.com/techmatters/terraso-mobile-client/assets/10799815/910c7809-da2d-4a2b-9dbb-2ff654c1dd87

**Comment by paulschreiber** [comment]
Filed an upstream bug: https://github.com/expo/expo/issues/29078
