### ISSUE TITLE
Implement design tutorial text for texture guide

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1535]
Update the texture guide screens to match[ Figma design](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=8336-12439&t=DvpDo5bKaKDFvXxa-0).

## Steps to find screen
1. Go to a site (unaffiliated, or affiliated with "texture" requirement)
2. Go to "soil" tab
3. in a depth, select "Texture"
4. Select info button

**Comment by CourtneyLee333** [comment]
@paulschreiber I think this looks fine for now. In a future enhancement I might like to put the graphic before the question, and have the screen auto-scroll down when an answer is selected. Otherwise, questions and next steps can be overlooked. It seems odd, too, that the paragraph headings are larger than the questions. I'll make an issue for these things.
