### ISSUE TITLE
[Offline] Create sync button & handle SiteNotesScreen's deleted required entities

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#2232]
### Acceptance Criteria
- When the offline feature flag is on, a "Sync: pull" button appears on most screens after login
- Pressing the sync button will get the most recent data from the server
- If you are on the "Edit Site Note" screen:
  - If someone deletes the note and you pull, you are navigated to the site's list of notes
  - If someone deletes the site and you pull, you are navigated back the the sites list screen (formerly known as home screen)
  - (On Android you'll also see a snackbar notification -- I expect this to be temporary once the actual design gets decided and implemented)
- If you are on any of the site tabs (Site, Slope, Soil, or Notes) or the "Texture" screen for a site, and someone deletes the site, you are navigated back to the sites list screen

**Comment by knipec** [comment]
Available to QA in v198

**Comment by DerekCaelin** [comment]
@knipec Courtney and I tested this!
- We deleted a note while another person was looking at the note, and we were booted back to the notes tab as expected.
- We deleted a site after navigating to it from a project, and were booted back to the project screen
- We deleted a site after navigating to it from the sites screen, and we were booted back to the sites screen. 
- A time when it didn't behave as expected:
   - We created a project with three sites
   - Device A looked at the sites list on the project screen
   - Device B looked at the soils tab of a site in the project
   - Device A deleted the site from the project site list
   - Device B synced, saw no change (expected to be booted to the project site list)
   - Device A pulled, site reappeared (expected to remain deleted)

We didn't test what happens when a project gets deleted - should we?
We realized that the bottom sheet on the sites list is able to expand to cover the entire map again, which should have been addressed by #1483

**Comment by knipec** [comment]
@DerekCaelin Huh, strange. I just went through the same steps and when Device B pulled, I did get booted to the project site list. And when Device B pulled, the site did not reappear.

**Comment by knipec** [comment]
And no, I haven't implemented any logic for deleted projects yet.

And hmm, not sure about what's going on with #1483 -- maybe a question for Paul when he gets back unless you think it's urgent?

**Comment by DerekCaelin** [comment]
We also tried to reproduce our wonky "undelete" experience and couldn't. Let's call this issue resolved and see if the issue happens again.
