### ISSUE TITLE
Select component design update

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#233]
NativeBase library uses bottom sheet for the select menu. Is this okay? Need to research best practices and decide if design needs to be updated. 

NOTE: When this decision is settled, we likely need to update modal forms to sheets to accommodate a non-dropdown selection (example: adding a custom depth interval in project management)

**Comment by CourtneyLee333** [comment]
The bottom sheet seems to be a common design pattern for select, and I'm fine with this. Picker component looks cool, but is deprecated in NativeBase library. Scrolling wheel is cool, but not accessible by keyboard. 
David:  I'm sure we find some other library where the select doesn't use a bottom sheet though, I'll make an issue to investigate this a bit after usability testing

**Comment by ltseng** [comment]
Let's keep https://github.com/techmatters/terraso-mobile-client/issues/536 in mind when we make a decision on this

**Comment by CourtneyLee333** [comment]
@david-code Where are we at with this? Is a bottom sheet picker an option for the select component? Ideally I'd do something like this: 


![Image](https://github.com/techmatters/terraso-mobile-client/assets/8915145/557472fb-8d12-496d-b665-ce68c7a03d2a)

**Comment by CourtneyLee333** [comment]
@shrouxm Tagging you here as well, see comments and questions above.

**Comment by david-code** [comment]
I took a quick look. It seems like react native wheel pickers are not super well supported right now. I found a few libraries in the [react native directory](https://reactnative.directory/?search=wheel+picker&order=stars), but they all seem to be not actively maintained and buggy. It might be worth it to take a closer look - it seems that a few picker library provides a wheel select on iOS but not android (because that is what the native `select` component looks like) - see [react-native-picker](https://github.com/lawnstarter/react-native-picker-select) for example.
