### ISSUE TITLE
Soil ID: Update layout of slope steepness module

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2515]
Updates to the slop module to be consistent with the soil cracks module. 

This change will also address: https://github.com/techmatters/terraso-mobile-client/issues/2362

### Acceptance Criteria
- [x] Move the  button below the slope steepness box
- [x] Change title to "ENTER STEEPNESS"
<img width="272" alt="image" src="https://github.com/user-attachments/assets/7613beaa-e168-4238-9e8b-8b5676294fe3">
<img width="272" alt="image" src="https://github.com/user-attachments/assets/eca45344-7204-414e-a9e8-991aa05f83a2">

**Comment by paulschreiber** [comment]
Please verify in 216 or later.

**Comment by CourtneyLee333** [comment]
This looks good to me.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 I wanted to confirm that this is ok? I reviewed the implementation in 223 and this is what I see. The button is right justified. 
<img src="https://github.com/user-attachments/assets/7fa6a6b9-ef40-4624-8b86-e94e7ff7c872" width="200px">

**Comment by CourtneyLee333** [comment]
@DerekCaelin No, the button got moved to the right after Paul did this work. Ruxandra was doing button component work and referred to the Capri design instead of the Post-Capri (easy thing to overlook.) I've created another ticket to put all the buttons on that section back to the left, so this one can stay closed.

**Comment by DerekCaelin** [comment]
Thanks for checking
