### ISSUE TITLE
Add supporting text for login screen for usability study

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#254]
Need some supporting text like "Welcome to LandPKS, click below to log in to your Terraso account"

**Mockup (Figma)**
https://www.figma.com/file/5nUT64WqA1i68J9TtmeqBv/LPKS-Login-screen-for-UT?type=design&node-id=0%3A1&mode=design&t=gtbGmxUxaDrCzusl-1

**Comment by Hanal-code** [comment]
Note that minor text tweak may come later.

**Comment by ltseng** [comment]
Is this ready for engineering @Hanal-code?

**Comment by Hanal-code** [comment]
@ltseng Yes

**Comment by shrouxm** [comment]
note (@Hanal-code): i made the login button text "CONTINUE WITH GOOGLE" in the linked PR, since in the current implementation it directly opens a google login screen and i thought it'd be more confusing if it said "CONTINUE WITH TERRASO". lmk if that is really bad and otherwise we can revisit when we've fleshed out the login options and what all these integrations will look like!

**Comment by Hanal-code** [comment]
@shrouxm Can you clarify that the new users will NOT be taken to the Terraso login screen to create an account -- meaning LPKS will not follow the existing Terraso SSO screen flow? 
I understood the current login behavior is applicable for the current Terraso users, not new Terraso users. 
If it was misunderstanding, I need to revisit the button label.

**Comment by Hanal-code** [comment]
@shrouxm here's the screenshot: 
<img width="361" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/92342777/c69af3b7-37bd-4e41-81d5-178a227f43e7">

I swapped the button in the Figma file as well. 

**re: sign-in process for long-term.** 
I agree with your feedback. We are still working on addressing that, but it's not the usability study question this time.
