### ISSUE TITLE
New projects not being saved to the backend

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#291]
I saved a project on the Android app (v1.0.1, Samsung Galaxy S10, Android 12) and it was not saved to the backend. Very easily replicable, and can provide screen recording if needed.

**Comment by david-code** [comment]
Garo's notes:
- revert https://github.com/techmatters/terraso-backend/pull/633/files#diff-0a005977d34be0e7cd07374b65858f3e7e33a56c95593daf794a961f15500cd6
- run `make makemigration`
- this fixes current error, but seems to be another error as well

**Comment by david-code** [comment]
@ltseng because the revert of the update to the upstream library fixed this bug, I was thinking of keeping the issue open. Instead of addressing the bug itself, which we have solved, the issue will be to either change the way we use the library to work with the updated upstream library version, or create a bug report on the upstream library repo if it seems like more of a problem that they should fix. I'd move the priority down to 2 then. Does that make sense to you?

**Comment by david-code** [comment]
Closed in favour of https://github.com/techmatters/terraso-backend/issues/752
