### ISSUE TITLE
Map pin icons are different sizes on iOS and Android; blurry on iOS

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#316]
## Description
The pins are enormous on iOS, but not on Android. The following screenshots have been taken on both iOS and Android at roughly the same scale, aka whatever scale the map is set to upon first opening the app.

Android

![Screenshot_20230822-163031_Terraso LandPKS.jpg](https://github.com/techmatters/terraso-mobile-client/assets/2730009/cf21096f-fc1e-46cc-ba01-23bec19b2402)

iOS

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/0c71e9d8-b25e-4b9c-9591-37771c33867c)

**Comment by shrouxm** [comment]
@paulschreiber can you look into this? i think the only relevant values should be in `dev-client/src/components/home/SiteMap.tsx`. we specify the size in these two places:
- when generating the static icon image here: https://github.com/techmatters/terraso-mobile-client/blob/e66af6f882b2d68b0a442459d099c680ef6e52e0/dev-client/src/components/home/SiteMap.tsx#L213-L217
- when specifying the layer styles here: https://github.com/techmatters/terraso-mobile-client/blob/e66af6f882b2d68b0a442459d099c680ef6e52e0/dev-client/src/components/home/SiteMap.tsx#L260-L265

i'm guessing one (hopefully not both 😱) of the values behaves differently per platform, so if you could find a set of values that creates the same size icon on android and iOS that should resolve the issue. See e.g. [here](https://www.figma.com/file/LnZIxeirOsPd5zsUBfJRAf/LandPKS-Design-Prototype-CURRENT-8%2F11%2F23?type=design&node-id=1062-42142&mode=dev) in the design for the expected size. (We aren't displaying the cluster icons or increasing the icon size when it is selected yet).

**Comment by paulschreiber** [comment]
Filed https://github.com/rnmapbox/maps/issues/3009

**Comment by paulschreiber** [comment]
Please retest on build 24 or later.

**Comment by ltseng** [comment]
Map markers on Android are now tiny. On iPad and iPhone, they're a good size, but blurry.

**Comment by ltseng** [comment]
This is leading to a secondary issue of me not being able to select the correct pin when two are moderately close together

https://github.com/techmatters/terraso-mobile-client/assets/2730009/3a621b8e-c055-40d9-9526-663e3d75ce32

**Comment by shrouxm** [comment]
ok soooooo i have tried:
- to coax rnmapbox to accept SVGs in [many](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md) [different](https://reactnative.dev/docs/image#resolveassetsource) [ways](https://www.npmjs.com/package/react-native-vector-image)
- to upload the SVG to mapbox studio
- to convert the SVG to [SDF](https://docs.mapbox.com/help/troubleshooting/using-recolorable-images-in-mapbox-maps/#what-are-signed-distance-fields-sdf)
- to convert PNGs to SDF
- to just use PNGs

and nothing works perfectly. it seems that the reason nothing works perfectly is outlined in this little snippet buried in the mapbox docs:

> Vector formats, like [SVGs](https://docs.mapbox.com/help/glossary/svg/), can also be good candidates for generating an SDF. Although SVGs are a vector image format, the Mapbox GL renderer cannot treat them as vector data in the same way it handles vector tiles or GeoJSON. Converting them to SDFs, however, makes it possible to add a scalable, recolorable SVG to your map.

while they mention earlier that SDFs are a _raster_ format and so look terrible when scaled. in fact even in the official mapbox docs for SDFs the demo map they display has jagged pixelated icons. the inability to render vector icons also explains why even if i upload an svg to mapbox studio, it will look blurry

so i think our only option is to programmatically pre-generate raster icons for each size and color we need at appropriate pixel densities for the running device. which will hopefully not be as difficult as it sounds because of RN's [PixelRatio](https://reactnative.dev/docs/pixelratio) function and the existing vector icon `getImageSource` method

i will attempt to implement this at a time that is later 👍 

i do feel like i'm missing something because this seems ridiculous, but at the same time the docs are clearly stating that they can't render vector symbols (even though the entire core innovation of Mapbox as a company is rendering maps from vector data)

**Comment by ltseng** [comment]
This is looking good on both Android and iOS now!
