### ISSUE TITLE
Go to Site link in project sites view doesn't go anywhere

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#323]
## Description
Clicking on the "Go to Site" link in a site card in the project sites view doesn't take you to the site dashboard

## Steps To Reproduce
1. Open project and switch to Sites tab
2. Click on "Go to Site" link in any site card

## Expected behavior
User should be taken to site dashboard for selected site

## Actual behavior
Nothing happens

## Additional context
![Screenshot_20230823-113630_Terraso LandPKS.jpg](https://github.com/techmatters/terraso-mobile-client/assets/2730009/04d4cc46-ddbb-4ce3-a980-df28f39145c9)

**Comment by CourtneyLee333** [comment]
@shrouxm The site card has been significantly updated since this very early iteration was implemented. It should be identical to the site card on the Sites list view on the home screen, with the addition of the quick menu icon. See the design here https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=224%3A20695&mode=design&t=tpjsZFeRbHtexLSY-1

**Comment by shrouxm** [comment]
yes! i updated it to the new design as part of the fix here: https://github.com/techmatters/terraso-mobile-client/pull/326

**Comment by CourtneyLee333** [comment]
Great!

**Comment by ltseng** [comment]
@shrouxm when this is ready to test, please assign back to me and @CourtneyLee333 (she'll handle the design review, I'll do the functional review)

**Comment by ltseng** [comment]
I see that the project sites list designs have been updated now, so this is not an applicable task anymore. Closing!
