### ISSUE TITLE
Enable building separate US and international versions of app

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#373]

**Comment by shrouxm** [comment]
@ltseng we're only going to be building one version of the app for MVP right? is high prio for january the right timeline for this, or are our wires crossed about what work this issue refers to?

**Comment by ltseng** [comment]
We need to build a US app and an international app. The US app will be delivered first, but as part of that work, I imagine we need to set the appropriate backend/database flags to indicate that a site is created in one version of the app vs. the other, plus restrict site creation to just the US for the US Soil ID app. I also imagine that this work would need to live in the US or international versions of the app. So, whether this issue is completed in January, vs. the other issues that are open for restricting boundaries or flagging when sites are created in one app or the other, is all implementation details to me, but the general direction of all this is that yes, we will need to deliver both. I can move all of these issues to February to allow you and David to focus on building more screens for now, though.
