### ISSUE TITLE
Add "None" option to lists in app

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#536]
When I've selected a project or role to filter the Sites list, I'm finding that I can't clear those filters without closing and reopening the app. 

https://github.com/techmatters/terraso-mobile-client/assets/2730009/01bdc349-0423-4c79-bbe4-c8f8c03ec0cc

This also happens in the Create Site form, specifically the Add to Project field. Both of these open up list components which do not have a "None" option. Let's add one.

Related/affected issue: https://github.com/techmatters/terraso-mobile-client/issues/233

**Comment by ltseng** [comment]
@CourtneyLee333 do you have a preference between adding an option to the selectable list for "No filter" or "Show all" and actually have a "Reset" button next to "Apply?

**Comment by CourtneyLee333** [comment]
This is a pattern that recurs throughout the app. My preference is to have an option on the selection list that is either blank or has the text "No filter". Looking at the implementation, it seems that "No filter" is best because the blank would essentially be invisible. When we get to data inputs and other forms, we'll need to change the verbiage or consider a different styling on the list to make "none" and option. (I've pointed this out in another ticket, which I think was the Site Creation form where once you choose a project to transfer the site to you can't clear the selection.)

**Comment by ltseng** [comment]
I'm going to change the name of this issue to better reflect this then. Thanks @CourtneyLee333!

**Comment by david-code** [comment]
Closing as I linked my PR against the wrong issue
