### ISSUE TITLE
Project members see "edit" pencil signifier for notes they did not create

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#709]
### App Version

66

### Platforms

- [x] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Only the note author and site owner/project manager should be able to see the edit button on a site note card. Only the note author can enter data into the text box on the site note edit screen. All of them can delete the note. Viewers, and project contributors who did not author the note in question, should not be able to see the edit button.

### Steps to Reproduce

1. As a project manager or contributor (User 1) for a project that has at least one site, make a note
2. Sign into a different user account (User 2) and view the notes for that same site.

### Expected behavior

Edit icon does not appear on the note that was taken by user 1

### Actual behavior

Edit icon does appear on the note that was taken by user 2. Fortunately, it is not possible for user 2 to make or save any edits.  (Is this a client side issue?)

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/a5b08c54-f9ce-4395-9dc2-e758f788d54b

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 yes, sorry! I accidentally assigned this ticket to QA instead of the other one I submitted.

**Comment by CourtneyLee333** [comment]
I noticed that as a contributor, I can tap another team member's note to open the full screen view with the close button. Since the note text does not get truncated on the main notes screen, it isn't necessary to be able to open the full screen view. I don't see this as a high priority, though, so I can create a bug report for later. 

However, as a Manager, I cannot edit or delete a contributor's note. I see the pencil icon, I can open the full screen view, but I cannot tap into the editor field and I only see the Close button.
