### ISSUE TITLE
data privacy info sheet - update text, reduce max height, connect x button to close behavior

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#755]
Update the data privacy screen to meet design.

## References
Dependent on:
- https://github.com/techmatters/terraso-mobile-client/issues/697

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-12993&t=G6FkzaLdYYCwCmxm-0)
<img src="https://github.com/techmatters/terraso-mobile-client/assets/10799815/6ffc041f-ff33-46b1-a1c7-dbe6f8435864" width="300">

## Acceptance Criteria
- [x] Text is revised to meet figma design
   - [ ] Data portal links to https://landpks.terraso.org/portal
   - [x] Privacy policy links to https://techmatters.org/privacy-policy/
- [x] Apply InfoOverlaySheet component, which should resolve
   - [x] Max height of sheet meets design
   - [x] Selecting the "X" button closes the sheet

**Comment by CourtneyLee333** [comment]
@DerekCaelin Just noting that there are references to the data portal in the privacy content. I think we should keep the reference, and create a Coming Soon page on the new site, so it's clear to people that one day the public data will be accessible. Otherwise, we need to completely rewrite what public and private means. Actually, the concept of public and private don't exist outside the web portal.

**Comment by DerekCaelin** [comment]
Adding this back into Capri because, as Courtney notes, the text links to a data portal that doesn't exist, it is critical for people to understand that their public data will be accessible somewhere, and it is relatively trivial to update text. @tm-ruxandra Please let me know if we should split the "text" and "behavior" aspects of this issue.

**Comment by tm-ruxandra** [comment]
@DerekCaelin for this eng estimate I'm fine with keeping them together.

**Comment by CourtneyLee333** [comment]
Just chiming in to say I updated the slug for the data portal page to match what's in this ticket.

**Comment by CourtneyLee333** [comment]
@tm-ruxandra this all looks good except one thing - the Data Portal link doesn't have the correct URL. It should go to https://landpks.terraso.org/portal.

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 that's an easy fix, will get it out shortly.
