### ISSUE TITLE
"Error saving Soil ID information" appears on launch

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#913]
### App Version

88 (but has appeared in earlier builds)

### Account

courtney@techmatters.org, lilly.tseng@gmail.com

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

The appearance of this issue often coincides with https://github.com/techmatters/terraso-mobile-client/issues/681, but filing this as its own separate issue.

### Steps to Reproduce

Launch app

### Expected behavior

App loads without any issues

### Actual behavior

"Error saving soil ID information" appears on bottom of screen, often accompanied by #681 as well.

### Additional context

Screen recording of issue can be seen in [this comment](https://github.com/techmatters/terraso-mobile-client/issues/681#issuecomment-1885748943)'s video.

**Comment by DerekCaelin** [comment]
From @shrouxm 

-the "error saving soil id information" message in issue #913 is because that's just the hardcoded message that shows up whenever there's any problem communicating with the server. we can/should have better error messages, but the rate of error messages will depend on how many bugs we merge
- #681 is similar in that the sites/projects are disappearing because:
- we haven't implemented offline storage yet, so they need to be fetched from the server on each app launch
- we merge bugs which make that fetch request fail

so we might see similar issues until we implement offline storage, or merge fewer bugs
- so possible action items to address these symptoms:
- manual testing before releasing app to internal testers. this is already something we ostensibly do, and there are no barriers to do this - besides that it's a manual process which we clearly haven't been very good at so far
  - automated testing to reduce the manual testing burden
  - implement better error messages
  - the last two both need some discovery

**Comment by DerekCaelin** [comment]
Closing this because:
- I can't replicate
- We are addressing underlying issues by doing unit testing https://github.com/techmatters/terraso-product/issues/604 and are working to improve error messages https://github.com/techmatters/terraso-product/issues/603
