### ISSUE TITLE
Sites list doesn't load all sites at once

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#961]
It's a little annoying when I try to scroll through what I think is a full list of my sites, but have to stop and scroll down a little further every couple seconds for more items in the list to load.

https://github.com/techmatters/terraso-mobile-client/assets/2730009/046d2da3-07b3-4a1a-b851-d9a91bbc45a3

**Comment by ltseng** [comment]
@CourtneyLee333 flagging this one for us.to think about. I'm not labeling it as Slim MVP yet because it's more an annoying cosmetic issue than anything, but let me know if you feel differently.

**Comment by paulschreiber** [comment]
A crash is most definitely not cosmetic. Any reproducible crash is P1.

**Comment by ltseng** [comment]
I was referring to the sites list having to load piece by piece. The crash is definitely not cosmetic, but I haven't been able to reproduce it yet. I filed that separately in #963.

**Comment by CourtneyLee333** [comment]
If it's a progressive load to help speed up the initial load of the screen, the tradeoff of a slight delay might not be bad. I'd like to more about what's happening and what the alternatives would be. I think in reality the user will choose to sort their sites in a meaningful to find the one they're looking for, rather than open the screen and immediately start scrolling and scrolling through the list's default sort. What is the default sort anyway? I can't remember which spec covers that.

**Comment by ltseng** [comment]
I don't think I ever specified a default sort in any of the specs or Github issues. I want to say that in practice, it's Date Last Modified (most recent), but since they all have the same last modified date, it's hard to tell 🙃

**Comment by DerekCaelin** [comment]
We'll hold off on this issue until we learn more from user feedback.
